### PR TITLE
Pr/001 missing filters url

### PR DESCRIPTION
**Pull request by pandec**
Missing filters url added - without that the package was getting 404.

And thanks for the great code!

### CODE REVIEW

**Comment by zbone3** [comment]
Thanks 👍 
Merged

**Comment by pandec** [comment]
No Problem.

Any chance you're going to push it to NPM? I copypasted it to my project with a disclaimer about the source, but I'd rather just use the original package instead ;)

**Comment by zbone3** [comment]
Sure I'll publish now with the new change you committed
Thanks

**Comment by zbone3** [comment]
Updated on npmjs

**Pull request merged**
